definitions:
  model.Contact:
    properties:
      emails:
        items:
          type: string
        type: array
      phoneNumbers:
        items:
          type: string
        type: array
      primaryContactId:
        type: integer
      secondaryContactIds:
        items:
          type: integer
        type: array
    type: object
  model.IdentityRequest:
    properties:
      email:
        type: string
      phoneNumber:
        type: string
    type: object
  model.IdentityResponse:
    properties:
      contact:
        $ref: '#/definitions/model.Contact'
    type: object
info:
  contact: {}
paths:
  /identify:
    post:
      consumes:
      - application/json
      description: This endpoint is used to return data related to email or phone
        number supplied
      parameters:
      - description: enter email and phone number
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.IdentityRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.IdentityResponse'
      summary: Return user data
swagger: "2.0"
